<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>DisplayCast</RootNamespace>
    <AssemblyName>DisplayCast</AssemblyName>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <Version>0.2.1</Version>
    <AssemblyTitle>DisplayCast 播控</AssemblyTitle>
    <Product>DisplayCast</Product>
    <Description>局域网显示设备播控软件</Description>
    <NoWarn>$(NoWarn);WFO0003</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="System.IO" />
    <Using Remove="System.Drawing" />
    <Using Remove="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\app.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
  </ItemGroup>

</Project>
